trusty-cms-3.3.6/config/routes.rb
TrustyCms::Application.routes.draw do
  root to: 'site#show_page'

  get '/rad_social/mail' => 'social_mailer#social_mail_form', as: :rad_social_mail_form
  post '/rad_social/mail' => 'social_mailer#create_social_mail', as: :rad_create_social_mail
  TrustyCms::Application.config.enabled_extensions.each { |ext|
  }
  namespace :admin do
    resources :pages do
      resources :children, :controller => 'pages'
      get 'remove', on: :member
    end
    resources :layouts do
      get 'remove', on: :member
    end
    resources :users do
      get 'remove', on: :member
    end
    resources :snippets do
      get :remove, on: :member
    end
    resources :password_resets
    post 'save-table-position' => "pages#save_table_position", as: "save_tables_position"

    resources :assets do
      get :remove, on: :member
      get :refresh, on: :collection
      post :regenerate, on: :collection
      put :refresh, on: :member
    end
    resources :page_attachments, :only => [:new] do
      get :remove, on: :member
    end
    resources :pages do
      get :remove, on: :member
      resources :page_attachments
    end
  end

  match 'admin/preview' => 'admin/pages#preview', :as => :preview, :via => [:post, :put]
  namespace :admin do
    resource :preferences
    resource :configuration, :controller => 'configuration'
    resources :extensions, :only => :index
    resources :page_parts
    resources :page_fields
    match '/reference/:type(.:format)' => 'references#show', :as => :reference, :via => :get

    resources :sites do
      get :remove, on: :member
      post :move_higher, on: :member
      post :move_lower, on: :member
      put :move_to_top, on: :member
      put :move_to_bottom, on: :member
    end
  end

  get 'admin' => 'admin/welcome#index', :as => :admin
  get 'admin/welcome' => 'admin/welcome#index', :as => :welcome
  match 'admin/login' => 'admin/welcome#login', :as => :login, :via => [:get, :post]
  get 'admin/logout' => 'admin/welcome#logout', :as => :logout
  get 'error/404' => 'site#not_found', :as => :not_found
  get 'error/500' => 'site#error', :as => :error
  get '*url' => 'site#show_page'

end

trusty-cms-3.3.6/app/controllers/admin/password_resets_controller.rb
class Admin::PasswordResetsController < ApplicationController
  no_login_required
  skip_before_action :verify_authenticity_token

  def create
    user = User.find_by_email(params[:email])
    if user
      user.send_password_reset
      redirect_to welcome_path, :notice => "Email sent with password reset instructions."
    else
      redirect_to welcome_path, :notice => "Email not registered. Double check your spelling or seek out your Admin."
    end
  end

  def edit
    @user = User.find_by_password_reset_token!(params[:id])
  end

  def update
    @user = User.find_by_password_reset_token!(params[:id])
    if @user.password_reset_sent_at < 2.hours.ago
      redirect_to new_password_reset_path, :alert => "Password reset has expired."
    elsif @user.update_attributes(password_params)
      redirect_to welcome_url, :notice => "Password has been reset!"
    else
      render :edit
    end
  end

private

  def password_params
    params.require(:user).permit(:password, :password_confirmation)
  end

end

trusty-cms-3.3.6/app/views/admin/password_resets/edit.html.haml
- body_classes << "single_form"

#single_form

  %h3= t('reset_your_password')

  = form_for @user, :url => admin_password_reset_path(params[:id]) do |f|
    - if @user.errors.any?
      .error_messages
        %h2 Form is invalid
        %ul
          - for message in @user.errors.full_messages
            %li= message
    %p
      %label{:for=>"password"}= t('password')
      = f.password_field :password
    %p
      %label{:for=>"password_confirmation"}= t('password_confirmation')
      = f.password_field :password_confirmation
    .actions= f.submit "Update Password"

  %p.version
  = t('powered_by')
  %a{ :href => "https://github.com/pgharts/trusty-cms" } TrustyCms CMS
  = t('version')
  = TrustyCms.loaded_via_gem? ? "#{TrustyCms::VERSION} (gem)." : "#{TrustyCms::VERSION}."

trusty-cms-3.3.6/app/views/admin/password_resets/new.html.haml
- body_classes << "single_form"

#single_form

  %h3= t('reset_your_password')

  = form_tag admin_password_resets_path, :method => :post do
    %p
      %label{:for=>"email"}= t('email')
      = text_field_tag :email, params[:email], :class => 'textbox', :maxlength => 70, :size => 70
    .actions
      = submit_tag "Reset Password"

  %p.version
  = t('powered_by')
  %a{ :href => "https://github.com/pgharts/trusty-cms" } TrustyCms CMS
  = t('version')
  = TrustyCms.loaded_via_gem? ? "#{TrustyCms::VERSION} (gem)." : "#{TrustyCms::VERSION}."