trusty-cms-3.3.6/config/routes.rb
TrustyCms::Application.routes.draw do
  root to: 'site#show_page'

  get '/rad_social/mail' => 'social_mailer#social_mail_form', as: :rad_social_mail_form
  post '/rad_social/mail' => 'social_mailer#create_social_mail', as: :rad_create_social_mail
  TrustyCms::Application.config.enabled_extensions.each { |ext|
  }
  namespace :admin do
    resources :pages do
      resources :children, :controller => 'pages'
      get 'remove', on: :member
    end
    resources :layouts do
      get 'remove', on: :member
    end
    resources :users do
      get 'remove', on: :member
    end
    resources :snippets do
      get :remove, on: :member
    end
    resources :password_resets
    post 'save-table-position' => "pages#save_table_position", as: "save_tables_position"

    resources :assets do
      get :remove, on: :member
      get :refresh, on: :collection
      post :regenerate, on: :collection
      put :refresh, on: :member
    end
    resources :page_attachments, :only => [:new] do
      get :remove, on: :member
    end
    resources :pages do
      get :remove, on: :member
      resources :page_attachments
    end
  end

  match 'admin/preview' => 'admin/pages#preview', :as => :preview, :via => [:post, :put]
  namespace :admin do
    resource :preferences
    resource :configuration, :controller => 'configuration'
    resources :extensions, :only => :index
    resources :page_parts
    resources :page_fields
    match '/reference/:type(.:format)' => 'references#show', :as => :reference, :via => :get

    resources :sites do
      get :remove, on: :member
      post :move_higher, on: :member
      post :move_lower, on: :member
      put :move_to_top, on: :member
      put :move_to_bottom, on: :member
    end
  end

  get 'admin' => 'admin/welcome#index', :as => :admin
  get 'admin/welcome' => 'admin/welcome#index', :as => :welcome
  match 'admin/login' => 'admin/welcome#login', :as => :login, :via => [:get, :post]
  get 'admin/logout' => 'admin/welcome#logout', :as => :logout
  get 'error/404' => 'site#not_found', :as => :not_found
  get 'error/500' => 'site#error', :as => :error
  get '*url' => 'site#show_page'

end

trusty-cms-3.3.6/app/models/user.rb
require 'digest/sha1'

class User < ActiveRecord::Base
  has_many :pages, :foreign_key => :created_by_id

  # Default Order
  default_scope {order("name")}

  # Associations
  belongs_to :created_by, :class_name => 'User'
  belongs_to :updated_by, :class_name => 'User'

  # Validations
  validates_uniqueness_of :login

  validates_confirmation_of :password, :if => :confirm_password?

  validates_presence_of :name, :login
  validates_presence_of :password, :password_confirmation, :if => :new_record?


  validates_length_of :name, :maximum => 100, :allow_nil => true
  validates_length_of :login, :within => 3..40, :allow_nil => true
  validates_length_of :password, :within => 5..40, :allow_nil => true, :if => :validate_length_of_password?
  validates_length_of :email, :maximum => 255, :allow_nil => true

  attr_writer :confirm_password

  def has_role?(role)
    respond_to?("#{role}?") && send("#{role}?")
  end

  def sha1(phrase)
    Digest::SHA1.hexdigest("--#{salt}--#{phrase}--")
  end

  def self.authenticate(login_or_email, password)
    user = where(["login = ? OR email = ?", login_or_email, login_or_email]).first
    user if user && user.authenticated?(password)
  end

  def authenticated?(password)
    self.password == sha1(password)
  end

  def after_initialize
    @confirm_password = true
  end

  def confirm_password?
    @confirm_password
  end

  def remember_me
    update_attribute(:session_token, sha1(Time.now + TrustyCms::Config['session_timeout'].to_i)) unless self.session_token?
  end

  def forget_me
    update_attribute(:session_token, nil)
  end

  def send_password_reset
    generate_token(:password_reset_token)
    update_attribute(:password_reset_sent_at, Time.zone.now)
    PasswordMailer.password_reset(self).deliver_now
  end

  private

  def generate_token(column)
    self[column] = SecureRandom.urlsafe_base64 if User.exists?(column => self[column])
  end

  def validate_length_of_password?
    new_record? or not password.to_s.empty?
  end

  before_create :encrypt_password
  def encrypt_password
    self.salt = Digest::SHA1.hexdigest("--#{Time.now}--#{login}--sweet harmonious biscuits--")
    self.password = sha1(password)
  end

  before_update :encrypt_password_unless_empty_or_unchanged
  def encrypt_password_unless_empty_or_unchanged
    user = self.class.find(self.id)
    case password
    when ''
      self.password = user.password
    when user.password
    else
      encrypt_password
    end
  end

end

trusty-cms-3.3.6/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ResourceController
  paginate_models
  only_allow_access_to :index, :show, :new, :create, :edit, :update, :remove, :destroy,
    :when => :admin,
    :denied_url => { :controller => 'pages', :action => 'index' },
    :denied_message => 'You must have administrative privileges to perform this action.'

  before_action :ensure_deletable, :only => [:remove, :destroy]

  def show
    redirect_to edit_admin_user_path(params[:id])
  end

  def update
    user_params = params[model_symbol].permit!
    if user_params && user_params['admin'] == false && model == current_user
      user_params.delete('admin')
      annouce_cannot_remove_self_from_admin_role
    end
    model.update_attributes!(user_params)
    response_for :update
  end

  def ensure_deletable
    if current_user.id.to_s == params[:id].to_s
      announce_cannot_delete_self
      redirect_to admin_users_path
    end
  end

  private

    def announce_cannot_delete_self
      flash[:error] = t('users_controller.cannot_delete_self')
    end

    def annouce_cannot_remove_self_from_admin_role
      flash[:error] = 'You cannot remove yourself from the admin role.'
    end
end

trusty-cms-3.3.6/app/helpers/admin/users_helper.rb
module Admin::UsersHelper
  def roles(user)
    roles = []
    roles << I18n.t('admin') if user.admin?
    roles << I18n.t('designer') if user.designer?
    roles.join(', ')
  end
end

trusty-cms-3.3.6/app/views/admin/users/_avatar.html.haml
#avatar
  = image_tag(gravatar_url(@user.email, :size=>"96px"), :class=>"avatar", :width=>96, :height=>96, :alt=>"")
  %p.caption
    Avatar provided by
    = link_to "gravatar.com", 'http://gravatar.com/site/signup/'

trusty-cms-3.3.6/app/views/admin/users/_choose_site.html.haml
- unless current_user.site
  %tr
    %th.label
      %label{:for=>"user_admin"} Can edit site
    %td.field{:style => 'text-align: left;'}
      = select :user, :site_id, [['<any>', '']] + Site.all.map { |s| [s.name, s.id] }
    %td.help
      A user with no site is able to act (to whatever extent their status allows) on any site.

trusty-cms-3.3.6/app/views/admin/users/_form.html.haml
= form_for [:admin, @user], :html => {class: "user_form"} do |f|
  = hidden_field "user", "lock_version"

  = render :partial => 'avatar' unless @user.new_record?

  = render_region :form_top, :locals => {:f => f}

  - render_region :form, :locals => {:f => f} do |form|
    - form.edit_name do
      %p
        = f.label :name, t('name')
        = f.text_field :name, :class => "textbox", :size => 32, :maxlength => 100

    - form.edit_email do
      %p
        = f.label :email, t('email_address') , :class => "optional"
        = f.text_field "email", :class => 'textbox', :size => 32, :maxlength => 255

    - form.edit_username do
      %p
        = f.label :login, t('username')
        = f.text_field "login", :class => "textbox", :size => 32, :maxlength => 40, :autocomplete => 'off'

    - form.edit_password do
      = render "password_fields", :f => f

    - form.edit_roles do
      %p
        %label.multi_option= t('roles')
        = f.check_box "admin", :class => "checkbox"
        = f.label :admin, t('admin'), :class => "checkbox"
        = f.check_box "designer", :class => "checkbox"
        = f.label :designer, t('designer'), :class => "checkbox"

    - form.edit_locale do
      %p
        = f.label :locale, t('language')
        = f.select "locale", available_locales_select

    - form.edit_notes do
      %p
        = f.label :notes, t('notes'), :class => "optional"
        ~ f.text_area "notes", :size => "53x4", :class => "textarea"

  - render_region :form_bottom, :locals => {:f => f} do |form_bottom|
    - form_bottom.edit_buttons do
      .buttons
        = save_model_button(@user)
        = save_model_and_continue_editing_button(@user)
        = t('or')
        = link_to t('cancel'), admin_users_path, class: 'alt'
    - form_bottom.edit_timestamp do
      = updated_stamp @user

trusty-cms-3.3.6/app/views/admin/users/_password_fields.html.haml
%p#display_password{:style=> (@user.new_record? or !@user.valid?) ? "display: none" : nil}
  %label= t('password')
  %span.value
    &bull;&bull;&bull;&bull;&bull;
    %a.action{:href=>"#", :onclick=>"$('#display_password').hide(); $('#change_password').show()"}= t('change')
.set#change_password{:style=> (!@user.new_record? && @user.valid?) ? "display: none" : nil}
  %p
    = f.label :password, t('new_password')
    = f.password_field "password", :class => "textbox big", :value => "", :size => 15, :maxlength => 40, :autocomplete => 'off'
  %p
    = f.label :password_confirmation, t('password_confirmation')
    = f.password_field "password_confirmation", :class => "textbox big", :value => "", :size => 15, :maxlength => 40, :autocomplete => 'off'
    - unless @user.new_record?
      %span
        = t('or')
        %a{:href=>"#", :class=>"warning", :onclick=>" $('#display_password').show(); $('#change_password').hide()"}= t('cancel', class: 'alt')

trusty-cms-3.3.6/app/views/admin/users/edit.html.haml
- @page_title = @user.name + ' ' + t('account') + ' - ' + default_page_title
- body_classes << 'edit_user'

- render_region :main do |main|
  - main.edit_header do
    %h1
      = t('edit_user')
  - main.edit_form do
    = render :partial => 'form'

trusty-cms-3.3.6/app/views/admin/users/index.html.haml
- @page_title = t('users') + ' - ' + default_page_title

= render_region :top

.outset
  %table.index#users
    %thead
      %tr
        - render_region :thead do |thead|
          - thead.title_header do
            %th.user== #{t('name')} / #{t('username')}
          - thead.roles_header do
            %th.roles= t('roles')
          - thead.actions_header do
            %th.actions{:style=>"width:9em"}= t('modify')
    %tbody
      - @users.each do |user|
        %tr[user]
          - render_region :tbody, :locals => {:user => user} do |tbody|
            - tbody.title_cell do
              %td.name
                = link_to image_tag(gravatar_url(user.email, :size=>"32px"), :class=>"avatar avatar_32x32", :width=>32, :height=>32, :alt=>""), edit_admin_user_url(user)
                = link_to user.name, edit_admin_user_url(user)
                %span.login (#{h user.login})
            - tbody.roles_cell do
              %td.roles= roles(user)
            - tbody.actions_cell do
              %td.actions
                - if user == current_user
                  %span.action.disabled= image('minus_disabled') + ' ' + t('remove')
                - else
                  = link_to image('minus') + ' ' + t('remove'), remove_admin_user_url(user), :class => "action"

- render_region :bottom do |bottom|
  - bottom.new_button do
    #actions
      = pagination_for(@users)
      %ul
        %li= link_to image('plus') + " " + t('new_user'), new_admin_user_url, :class => 'action_button'

trusty-cms-3.3.6/app/views/admin/users/new.html.haml
- render_region :main do |main|
  - main.edit_header do
    %h1
      = t('new_user')
  - main.edit_form do
    = render :partial => 'form'

trusty-cms-3.3.6/app/views/admin/users/remove.html.haml
%h1= t('remove_user')

%p
  = t('text.users.remove_warning')

%table.index#users
  %tbody
    %tr.node.level_1
      %td.user
        %span.title= @user.name

= form_for [:admin, @user], :html => { :method => :delete, 'data-onsubmit_status'=>"Removing user&#8230;" } do
  .buttons
    %input.button{:type=>"submit", :value => t('delete_user')}/
    = t('or')
    = link_to t('cancel'), admin_users_path, class: 'alt'