trusty-cms-3.3.6/config/routes.rb
TrustyCms::Application.routes.draw do
  root to: 'site#show_page'

  get '/rad_social/mail' => 'social_mailer#social_mail_form', as: :rad_social_mail_form
  post '/rad_social/mail' => 'social_mailer#create_social_mail', as: :rad_create_social_mail
  TrustyCms::Application.config.enabled_extensions.each { |ext|
  }
  namespace :admin do
    resources :pages do
      resources :children, :controller => 'pages'
      get 'remove', on: :member
    end
    resources :layouts do
      get 'remove', on: :member
    end
    resources :users do
      get 'remove', on: :member
    end
    resources :snippets do
      get :remove, on: :member
    end
    resources :password_resets
    post 'save-table-position' => "pages#save_table_position", as: "save_tables_position"

    resources :assets do
      get :remove, on: :member
      get :refresh, on: :collection
      post :regenerate, on: :collection
      put :refresh, on: :member
    end
    resources :page_attachments, :only => [:new] do
      get :remove, on: :member
    end
    resources :pages do
      get :remove, on: :member
      resources :page_attachments
    end
  end

  match 'admin/preview' => 'admin/pages#preview', :as => :preview, :via => [:post, :put]
  namespace :admin do
    resource :preferences
    resource :configuration, :controller => 'configuration'
    resources :extensions, :only => :index
    resources :page_parts
    resources :page_fields
    match '/reference/:type(.:format)' => 'references#show', :as => :reference, :via => :get

    resources :sites do
      get :remove, on: :member
      post :move_higher, on: :member
      post :move_lower, on: :member
      put :move_to_top, on: :member
      put :move_to_bottom, on: :member
    end
  end

  get 'admin' => 'admin/welcome#index', :as => :admin
  get 'admin/welcome' => 'admin/welcome#index', :as => :welcome
  match 'admin/login' => 'admin/welcome#login', :as => :login, :via => [:get, :post]
  get 'admin/logout' => 'admin/welcome#logout', :as => :logout
  get 'error/404' => 'site#not_found', :as => :not_found
  get 'error/500' => 'site#error', :as => :error
  get '*url' => 'site#show_page'

end

trusty-cms-3.3.6/app/models/snippet.rb
class Snippet < ActiveRecord::Base

  # Default Order
  default_scope {order('name')}

  # Associations
  belongs_to :created_by, :class_name => 'User'
  belongs_to :updated_by, :class_name => 'User'

  # Validations
  validates_presence_of :name
  validates_length_of :name, :maximum => 100
  validates_length_of :filter_id, :maximum => 25, :allow_nil => true
  validates_format_of :name, :with => %r{\A\S*\z}
  validates_uniqueness_of :name

  object_id_attr :filter, TextFilter

  def after_initialize
    self.filter_id ||= TrustyCms::Config['defaults.snippet.filter'] if new_record?
  end

end

trusty-cms-3.3.6/app/controllers/admin/snippets_controller.rb
class Admin::SnippetsController < Admin::ResourceController
  paginate_models
  only_allow_access_to :index, :show, :new, :create, :edit, :update, :remove, :destroy,
    :when => [:designer, :admin],
    :denied_url => { :controller => 'admin/pages', :action => 'index' },
    :denied_message => 'You must have designer privileges to perform this action.'
  
end

trusty-cms-3.3.6/app/views/admin/snippets/_choose_site.html.haml
- unless current_user.site
  %p{:style => 'float: left; margin-right: 32px'}
    %label{:for=>"snippet_site_id", :Class => "admin_only"}
      Site
      - sites = Site.all.map { |s| [s.name, s.id] }
      = select :snippet, :site_id, sites, :include_blank => Snippet.is_shareable?, :selected => @snippet.site_id || current_site.id

trusty-cms-3.3.6/app/views/admin/snippets/_form.html.haml
= form_for [:admin, @snippet], :html => {'data-onsubmit_status' => onsubmit_status(@snippet)} do |f|
  = f.hidden_field :lock_version
  = render_region :form_top, :locals => {:f => f}
  .form_area
    - render_region :form, :locals => {:f => f} do |form|
      - form.edit_title do
        %p.title
          = f.label :name, t('name')
          = f.text_field :name, :class => 'textbox activate', :maxlength => 100
      - form.edit_content do
        %p.content
          = f.label :content, t('body')
          ~ f.text_area :content, :class => "textarea large", :style => "width: 100%"
      - form.edit_filter do
        .set
          %p
            %span.reference_links
              == #{t('reference')}:
              %span{:id => "tag_reference_link"}
                = link_to t('available_tags'), admin_reference_url(:tags), id: 'tag_reference'
  - render_region :form_bottom, :locals => {:f => f} do |form_bottom|
    - form_bottom.edit_buttons do
      .buttons{:style=>"clear: left"}
        = save_model_button(@snippet)
        = save_model_and_continue_editing_button(@snippet)
        = t('or')
        = link_to t('cancel'), admin_snippets_url
    - form_bottom.edit_timestamp do
      = updated_stamp @snippet

trusty-cms-3.3.6/app/views/admin/snippets/_popups.html.haml
- content_for :popups do
  #popup_window
    .outer
      .content

trusty-cms-3.3.6/app/views/admin/snippets/edit.html.haml
- @page_title = @snippet.name + ' ' + t('snippet') + ' - ' + default_page_title

- render_region :main do |main|
  - main.edit_header do
    %h1= t('edit_snippet')  
  - main.edit_form do
    = render :partial => 'form'
  - main.edit_popups do
    = render :partial => "popups"

- content_for 'page_scripts'

trusty-cms-3.3.6/app/views/admin/snippets/index.html.haml
- @page_title = t('snippets') + ' - ' + default_page_title

.outset
  = render_region :top
  %table.index#snippets
    %thead
      %tr
        - render_region :thead do |thead|
          - thead.title_header do
            %th.name= t('snippet')
          - thead.actions_header do
            %th.actions{:style=>"width:9em"}= t('modify')
    %tbody
      - if @snippets.any?
        - @snippets.each do |snippet|
          %tr[snippet]
            - render_region :tbody, :locals => {:snippet => snippet} do |tbody|
              - tbody.title_cell do
                %td.name
                  = link_to image('snippet', :alt => '') + ' ' + snippet.name, edit_admin_snippet_url(snippet)
              - tbody.actions_cell do
                %td.actions
                  = link_to image('minus') + ' ' + t('remove'), remove_admin_snippet_url(snippet), :class => "action"
      - else
        %tr
          %td.empty{:colspan => admin.snippet.index.tbody.length}= t('no_snippets')

- render_region :bottom do |bottom|
  - bottom.new_button do
    #actions
      = pagination_for(@snippets)
      %ul
        %li= link_to image('plus') + " " + t('new_snippet'), new_admin_snippet_url, :class => 'action_button'

trusty-cms-3.3.6/app/views/admin/snippets/new.html.haml
- render_region :main do |main|
  - main.edit_header do
    %h1= t('new_snippet')  
  - main.edit_form do
    = render :partial => 'form'
  - main.edit_popups do
    = render :partial => "popups"

- content_for 'page_scripts'

trusty-cms-3.3.6/app/views/admin/snippets/remove.html.haml
%h1= t('remove_snippet')

%p 
  = t('text.snippets.remove_warning')

%table.index#snippets
  %tbody
    %tr.node.level_1
      %td.snippet
        = image('snippet', :alt => "")
        %span.title= @snippet.name

= form_for [:admin, @snippet], :html => {:method => :delete, 'data-onsubmit_status'=>"Removing snippet&#8230;"} do
  .buttons
    %input.button{:type=>"submit", :value => t('delete_snippet')}/
    = t('or')
    = link_to t('cancel'), admin_snippets_url