trusty-cms-3.3.6/config/routes.rb
TrustyCms::Application.routes.draw do
  root to: 'site#show_page'

  get '/rad_social/mail' => 'social_mailer#social_mail_form', as: :rad_social_mail_form
  post '/rad_social/mail' => 'social_mailer#create_social_mail', as: :rad_create_social_mail
  TrustyCms::Application.config.enabled_extensions.each { |ext|
  }
  namespace :admin do
    resources :pages do
      resources :children, :controller => 'pages'
      get 'remove', on: :member
    end
    resources :layouts do
      get 'remove', on: :member
    end
    resources :users do
      get 'remove', on: :member
    end
    resources :snippets do
      get :remove, on: :member
    end
    resources :password_resets
    post 'save-table-position' => "pages#save_table_position", as: "save_tables_position"

    resources :assets do
      get :remove, on: :member
      get :refresh, on: :collection
      post :regenerate, on: :collection
      put :refresh, on: :member
    end
    resources :page_attachments, :only => [:new] do
      get :remove, on: :member
    end
    resources :pages do
      get :remove, on: :member
      resources :page_attachments
    end
  end

  match 'admin/preview' => 'admin/pages#preview', :as => :preview, :via => [:post, :put]
  namespace :admin do
    resource :preferences
    resource :configuration, :controller => 'configuration'
    resources :extensions, :only => :index
    resources :page_parts
    resources :page_fields
    match '/reference/:type(.:format)' => 'references#show', :as => :reference, :via => :get

    resources :sites do
      get :remove, on: :member
      post :move_higher, on: :member
      post :move_lower, on: :member
      put :move_to_top, on: :member
      put :move_to_bottom, on: :member
    end
  end

  get 'admin' => 'admin/welcome#index', :as => :admin
  get 'admin/welcome' => 'admin/welcome#index', :as => :welcome
  match 'admin/login' => 'admin/welcome#login', :as => :login, :via => [:get, :post]
  get 'admin/logout' => 'admin/welcome#logout', :as => :logout
  get 'error/404' => 'site#not_found', :as => :not_found
  get 'error/500' => 'site#error', :as => :error
  get '*url' => 'site#show_page'

end

trusty-cms-3.3.6/app/models/asset.rb
class Asset < ActiveRecord::Base
  include Paperclip::Glue

  has_many :page_attachments, :dependent => :destroy
  has_many :pages, :through => :page_attachments
  has_site if respond_to? :has_site

  belongs_to :created_by, :class_name => 'User'
  belongs_to :updated_by, :class_name => 'User'

  default_scope {order("created_at DESC")}

  scope :latest, lambda { |limit|
    order("created_at DESC").limit(limit)
  }

  scope :of_types, lambda { |types|
    mimes = AssetType.slice(*types).map(&:mime_types).flatten
    Asset.select { |x| mimes.include?(x.asset_content_type) }
  }

  scope :matching, lambda { |term|
    where(["LOWER(assets.asset_file_name) LIKE (:term) OR LOWER(title) LIKE (:term) OR LOWER(caption) LIKE (:term)", {:term => "%#{term.downcase}%" }])
  }

  scope :excepting, lambda { |assets|
    if assets.any?
      assets = assets.split(',') if assets.is_a?(String)
      asset_ids = assets.first.is_a?(Asset) ? assets.map(&:id) : assets
      where(["assets.id NOT IN(#{asset_ids.map{ '?' }.join(',')})", *asset_ids])
    else
      {}
    end
  }

  has_attached_file :asset,
                    :styles => lambda { |attachment|
                      AssetType.for(attachment).paperclip_styles
                    },
                    :processors => lambda { |asset|
                      asset.paperclip_processors
                    },
                    :whiny => false,
                    :storage => TrustyCms.config["paperclip.storage"],
                    :path => TrustyCms.config["paperclip.path"],
                    :url => TrustyCms.config["paperclip.url"],
                    :fog_credentials =>
                        TrustyCmsClippedExtension::Cloud.credentials,
                    :fog_directory => TrustyCms.config["paperclip.fog.directory"],
                    :fog_public => TrustyCms.config["paperclip.fog.public?"] || true,
                    :fog_host => TrustyCmsClippedExtension::Cloud.host,
                    :fog_file => {
                        'Cache-Control' => 'max-age=2419200'
                        #'Expires'       => 1.month.from_now.httpdate
                    }

  validates_attachment_content_type :asset, :content_type => ["application/zip", "image/jpg", "image/jpeg", "image/png", "image/gif", "application/pdf", "application/javascript", "text/javascript", "text/css"]

  before_save :assign_title
  before_save :assign_uuid

  after_post_process :read_dimensions

  validates_attachment_presence :asset, :message => "You must choose a file to upload!"
  if TrustyCms.config["paperclip.skip_filetype_validation"] != "true" && TrustyCms.config['paperclip.content_types']
    validates_attachment_content_type :asset, :content_type => TrustyCms.config["paperclip.content_types"].gsub(' ','').split(',')
  else
    validates_attachment_presence :asset, :message => "Your uploaded file must have an extension in its name!"
  end
  validates_attachment_size :asset, :less_than => ( TrustyCms.config["assets.max_asset_size"] || 5 ).to_i.megabytes

  def asset_type
    AssetType.for(asset)
  end
  delegate :paperclip_processors, :paperclip_styles, :style_dimensions, :style_format, :to => :asset_type

  def thumbnail(style_name='original')
    return asset.url if style_name.to_sym == :original
    return asset.url(style_name.to_sym) if has_style?(style_name)
    return asset_type.icon(style_name)
  end

  def has_style?(style_name='original')
    style_name == 'original' || paperclip_styles.keys.include?(style_name.to_sym)
  end

  def basename
    File.basename(asset_file_name, ".*") if asset_file_name
  end

  def extension(style_name='original')
     if style_name == 'original'
       return original_extension
     elsif style = paperclip_styles[style_name.to_sym]
       return style.format
     else
       return original_extension
     end
  end

  def original_extension
    return asset_file_name.split('.').last.downcase if asset_file_name
  end

  def attached_to?(page)
    pages.include?(page)
  end

  def original_geometry
    @original_geometry ||= Paperclip::Geometry.new(original_width, original_height)
  end

  def geometry(style_name='original')
    raise Paperclip::StyleError, "Requested style #{style_name} is not defined for this asset." unless has_style?(style_name)
    @geometry ||= {}
    begin
      @geometry[style_name] ||= if style_name.to_s == 'original'
        original_geometry
      else
        style = self.asset.styles[style_name.to_sym]
        original_geometry.transformed_by(style.geometry)    # this can return dimensions for fully specified style sizes but not for relative sizes when there are no original dimensions
      end
    rescue Paperclip::TransformationError => e
      Rails.logger.warn "geometry transformation error: #{e}"
      original_geometry                                     # returns a blank geometry if the real geometry cannot be calculated
    end
  end

  def aspect(style_name='original')
    geometry(style_name).aspect
  end

  def orientation(style_name='original')
    a = aspect(style_name)
    case
    when a == nil?
      'unknown'
    when a < 1.0
      'vertical'
    when a > 1.0
      'horizontal'
    else
      'square'
    end
  end

  def width(style_name='original')
    geometry(style_name).width.to_i
  end

  def height(style_name='original')
    geometry(style_name).height.to_i
  end

  def square?(style_name='original')
    geometry(style_name).square?
  end

  def vertical?(style_name='original')
    geometry(style_name).vertical?
  end

  def horizontal?(style_name='original')
    geometry(style_name).horizontal?
  end

  def dimensions_known?
    original_width? && original_height?
  end

private

  # at this point the file queue will not have been written
  # but the upload should be in place. We read dimensions from the
  # original file and calculate thumbnail dimensions later, on demand.

  def read_dimensions
    if image?
      if file = asset.queued_for_write[:original]
        geometry = Paperclip::Geometry.from_file(file)
        self.original_width = geometry.width
        self.original_height = geometry.height
        self.original_extension = File.extname(file.path)
      end
    end
    true
  end

  def assign_title
    self.title = self.asset_file_name.downcase.sub(self.original_extension, "").sub(".", "")
  end

  def assign_uuid
    self.uuid = UUIDTools::UUID.timestamp_create.to_s unless uuid?
  end

  class << self
    def known_types
      AssetType.known_types
    end

    # searching and pagination moved to the controller

    def find_all_by_asset_types(asset_types, *args)
      with_asset_types(asset_types) { where *args }
    end

    def count_with_asset_types(asset_types, *args)
      with_asset_types(asset_types) { where(*args).count }
    end

    def with_asset_types(asset_types, &block)
      w_asset_types = AssetType.conditions_for(asset_types)
      with_scope(where(:conditions => ["#{w_asset_types} = ?", block]))
    end
  end

  # called from AssetType to set type_condition? methods on Asset
  def self.define_class_method(name, &block)
    eigenclass.send :define_method, name, &block
  end

  # returns the return value of class << self block, which is self (as defined within that block)
  def self.eigenclass
    class << self; self; end
  end

  # for backwards compatibility
  def self.thumbnail_sizes
    AssetType.find(:image).paperclip_styles
  end

  def self.thumbnail_names
    thumbnail_sizes.keys
  end

  # this is a convenience for image-pickers
  def self.thumbnail_options
    asset_sizes = thumbnail_sizes.collect{|k,v|
      size_id = k
      size_description = "#{k}: "
      size_description << (v.is_a?(Array) ? v.join(' as ') : v)
      [size_description, size_id]
    }.sort_by{|pair| pair.last.to_s}
    asset_sizes.unshift ['Original (as uploaded)', 'original']
    asset_sizes
  end

end

trusty-cms-3.3.6/app/controllers/admin/assets_controller.rb
class Admin::AssetsController < Admin::ResourceController
  paginate_models(:per_page => 50)
  COMPRESS_FILE_TYPE = ["image/jpeg", "image/png", "image/gif", "image/svg+xml"]

  def index
    assets = Asset.order("created_at DESC")
    @page = Page.find(params[:page_id]) if params[:page_id]

    @term = params[:search] || ''
    assets = assets.matching(@term) if @term && !@term.blank?

    @types = params[:filter] ? params[:filter].split(",") : []
    if @types.include?('all')
      params[:filter] = nil
    elsif @types.any?
      assets = assets.of_types(@types)
    end

    @assets = paginated? ? assets.paginate(pagination_parameters) : assets.all
    respond_to do |format|

      format.js {
        @page = Page.find_by_id(params[:page_id])
        render :partial => 'asset_table', :locals => {:with_pagination => true}
      }
      format.html {
        render
      }
    end
  end

  def create
    @assets, @page_attachments = [], []
    compress = current_site.try(:compress) ? current_site.compress : true
    asset_params[:asset][:asset].to_a.each do |uploaded_asset|
      if uploaded_asset.content_type == "application/octet-stream"
        flash[:notice] = "Please only upload assets that have a valid extension in the name."
      else
        uploaded_asset = compress(uploaded_asset) if $kraken.api_key.present? && COMPRESS_FILE_TYPE.include?(uploaded_asset.content_type) && compress
        @asset = Asset.create(:asset => uploaded_asset, :caption => asset_params[:asset][:caption])
        if params[:for_attachment]
          @page = Page.find_by_id(params[:page_id]) || Page.new
          @page_attachments << @page_attachment = @asset.page_attachments.build(:page => @page)
        end
        @assets << @asset
      end
    end
    if asset_params[:for_attachment]
      render :partial => 'admin/page_attachments/attachment', :collection => @page_attachments
    else
      response_for :create
    end
  end

  def refresh
    if asset_params[:id]
      @asset = Asset.find(params[:id])
      @asset.asset.reprocess!
      flash[:notice] = t('clipped_extension.thumbnails_refreshed')
      redirect_to edit_admin_asset_path(@asset)
    else
      render
    end
  end

  only_allow_access_to :regenerate,
    :when => [:admin],
    :denied_url => { :controller => 'admin/assets', :action => 'index' },
    :denied_message => 'You must have admin privileges to refresh the whole asset set.'

  def regenerate
    Asset.all.each { |asset| asset.asset.reprocess! }
    flash[:notice] = t('clipped_extension.all_thumbnails_refreshed')
    redirect_to admin_assets_path
  end

private
  def compress(uploaded_asset)
    data = $kraken.upload(uploaded_asset.tempfile.path, 'lossy' => true)
    File.write(uploaded_asset.tempfile, open(data.kraked_url).read, { :mode => 'wb' })
    uploaded_asset
  end

  def asset_params
    params.permit(:id, :for_attachment, :asset => [:caption, :for_attachment, :asset => []])
  end
end

trusty-cms-3.3.6/app/views/admin/assets/_asset.html.haml
- asset ||= @asset
- asset_type = asset.image? ? "image" : "link"

%li{:class => "#{asset_type} asset", :id => "asset_#{asset.id}"}
  .front
    .thumbnail= image_tag asset.thumbnail(:thumbnail)
  .back
    .title= asset.title
    %ul.actions
      %li
        = link_to t('clipped_extension.edit'), edit_admin_asset_url(asset), :class => 'edit_asset'
        = link_to t('clipped_extension.remove'), remove_admin_asset_url(asset), :class => 'remove_asset'

trusty-cms-3.3.6/app/views/admin/assets/_asset_table.html.haml
- assets ||= @assets
- page ||= @page
- with_pagination ||= false

- if assets.empty?
  %p
    = t("clipped_extension.no_assets")
- else
  - if with_pagination && assets.respond_to?(:total_pages) && assets.total_pages > 1
    = pagination_for(assets, pagination_parameters.merge(:depaginate => false, :params => {:controller => 'admin/assets', :action => 'index', :id => nil, :format => 'js'}))

  %ul
    - assets.each_with_index do |asset, index|
      - asset_type = asset.image? ? "image" : "link"
      %li{:class => "#{asset_type} asset", :id => "asset_#{asset.id}"}
        .front
          .thumbnail= image_tag asset.thumbnail(:thumbnail)
        .back
          .title
            = asset.title
          %ul.actions
            - if @page
              %li= asset_insertion_link(asset)
              %li= asset_attachment_link(asset)
            - else
              %li= link_to t('clipped_extension.edit'), admin_asset_path(asset), :class => 'edit'
              %li= link_to t("clipped_extension.remove"), remove_admin_asset_path(asset), :class => "delete"
            
  - if with_pagination && assets.respond_to?(:total_pages) && assets.total_pages > 1
    = pagination_for(assets, pagination_parameters.merge(:depaginate => false, :param_name => 'p', :params => {:controller => 'admin/assets', :action => 'index', :id => nil, :format => 'js', :page_id => (page && page.id), :pp => assets.per_page }))

trusty-cms-3.3.6/app/views/admin/assets/_errors.html.haml
- if @asset.errors && !@asset.errors.empty?
  %p#asset_errors
    %strong= t("clipped_extension.asset_errors", :errors => @asset.errors.full_messages.to_sentence)

trusty-cms-3.3.6/app/views/admin/assets/_form.html.haml
= render_region :form_top
- render_region :form do |form|
  - form.edit_title do
    %fieldset.title
  - form.edit_metadata do
    .drawer
      .drawer_contents#attributes
        %table.fieldset
          %tr
            %th.label
              %label{ :for => "asset_caption" }
                = t("clipped_extension.caption")
            %td.field
              = f.text_field :caption, :class => 'textbox', :maxlength => 255
          = render_region :extended_metadata, :locals => {:f => f}
      .drawer_handle
        %a.toggle.more{:href=>'#attributes', :rel=>"toggle[attributes]"}
          = t('more')

trusty-cms-3.3.6/app/views/admin/assets/_page_assets.html.haml
- unless @page.assets.empty?
  - @page.page_attachments.each do |attachment|
    = render :partial => 'admin/assets/asset', :locals => { :attachment => attachment }
- else
  %li
    %p.note
      = t("clipped_extension.no_attached_assets")

%script{ :type => "text/javascript" }
  Asset.MakeDraggables();

= sortable_element 'attachments', :url => reorder_assets_url(@page), :constraint => 'horizontal', :handle => 'reorder', :ghosting => false, :complete => visual_effect(:highlight, 'assets')

trusty-cms-3.3.6/app/views/admin/assets/_search.html.haml
= form_tag(admin_assets_path, :id=>'filesearchform', :method => 'get', :class=>"search") do
  - if @page
    = hidden_field_tag "page_id", @page.id
    = hidden_field_tag "p", params['p'] || 1
    = hidden_field_tag "pp", params['pp'] || 20

  .asset_filters
    = link_to t("asset_types.all"), admin_assets_url, :id => "select_all", :class => params[:filter].blank? ? "deselective pressed" : "deselective"
    - AssetType.all.each do |type|
      - unless type.name == :other
        = link_to t("asset_types.#{type.plural}"), admin_assets_url(:filter => type.name), :rel => type.name.to_s, :class => params[:filter] == type.name.to_s ? "selective pressed" : "selective"
  .right
    %input{:type=>"search", :id => 'filesearchforminput', :class=>"search", :name=>"search", :value=>h(params[:search]), :placeholder=>"Search", :results=>0, :size=>30}
  
  #type_boxes{:style => "display: none"}
    - AssetType.all.each do |type|
      = check_box_tag 'filter[]',  type.name.to_s, false, :id => "#{type.name}-check", :class => 'selective'

trusty-cms-3.3.6/app/views/admin/assets/_search_results.html.haml
%ul#search_list
  - unless @assets.empty?
    - @assets.each do |asset| 
      =# render :partial => 'asset', :locals => { :asset => asset, :page => @page }
      = render :partial => 'admin/assets/asset', :locals => { :asset_url => asset.asset.url, :asset_id => asset.id, :asset_type => 'image', :asset_title => asset.title, :asset_thumbnail => asset.thumbnail(:thumbnail), :page => @page }

  - else
    %li
      %p.note
        = t("clipped_extension.no_assets_found")
      
%script
  Asset.MakeDroppables();
  Asset.MakeDraggables();
  Event.addBehavior({ '.asset a' : Asset.DisableLinks, 'a.add_asset' : Asset.AddToPage });

  

trusty-cms-3.3.6/app/views/admin/assets/edit.html.haml
= stylesheet_link_tag 'admin/assets'
= render_region :top 

- render_region :main do |main|
  - main.edit_header do
    %h1= t("clipped_extension.asset_edit_title")
  
  - main.edit_form do
    - form_for :asset, :url => admin_asset_path(@asset), :html => { :method => "put", :multipart => true } do |f|
      .form_area
        = render :partial => "form", :locals => { :f => f }
        
        %div.content
          %fieldset
            %label.filename
              = "#{t("clipped_extension.filename")}: #{@asset.asset_file_name unless @asset.new_record?}"
          %p.asset
            - display_size = TrustyCms::config['assets.display_size'] || 'normal'
            = image_tag @asset.thumbnail(display_size.to_sym), :class => 'preview'

          = updated_stamp @asset
        
        %fieldset.upload
          %label.upload
            = t("clipped_extension.replace_file")
          = f.file_field :asset, :class => "", :style => "width: 100%"
        
        .buttons
          = save_model_button(@asset)
          = save_model_and_continue_editing_button(@asset)
          = t("or")
          = link_to t("cancel"), admin_assets_path
  
  - main.edit_regenerate do
    - if current_user.admin? or current_user.designer?
      %fieldset= t("clipped_extension.regenerate_thumbnails")
      
      - form_tag refresh_admin_asset_path(@asset), :method => :put do
        %p.asset_buttons
          %input.button{ :type => "submit", :value => t("clipped_extension.regenerate") }

trusty-cms-3.3.6/app/views/admin/assets/index.html.haml
= stylesheet_link_tag 'admin/assets'
= javascript_include_tag 'admin/assets_admin'

- content_for :toolbar do
  = render 'search'

.outset
  #assets_table.assets
    = render :partial => 'asset_table', :locals => { assets: @assets, with_pagination: true }
  %p{style: 'clear: both; height: 2em'} &nbsp;
  
- render_region :bottom do |bottom|
  #actions
    %ul
      %li= link_to((image('upload') + ' ' + t('clipped_extension.upload_asset')), new_admin_asset_path)

trusty-cms-3.3.6/app/views/admin/assets/new.html.haml
= stylesheet_link_tag 'admin/assets'
= render_region :top 

- render_region :main do |main|
  - main.edit_header do
    %h1= t("clipped_extension.new_asset")

    - main.edit_form do
      - form_for :asset, :url => admin_assets_path, :html => { :method => "post", :multipart => true } do |f|

        = render :partial => "form", :locals => { :f => f }

        %fieldset
          %label= t("clipped_extension.choose_file")
          = f.file_field :asset, :style => "width: 100%", :multiple => true

        .buttons
          = save_model_button(@asset)
          = save_model_and_continue_editing_button(@asset)
          = t("or")
          = link_to t("cancel"), admin_assets_path

    - main.edit_regenerate do
      &nbsp;

trusty-cms-3.3.6/app/views/admin/assets/refresh.html.haml
= stylesheet_link_tag 'admin/assets'

%h1
  = t("clipped_extension.refresh_assets")
%p.confirmation
  = t("clipped_extension.confirm_refresh_assets")
%p.confirmation
  =t('clipped_extension.refresh_assets_rake_task')

%form{:action => regenerate_admin_assets_path, :method => :post}
  .buttons
    %input.button{:type => "submit", :value => t("clipped_extension.refresh_assets")}
    = t("or")
    = link_to t("cancel"), admin_assets_path

trusty-cms-3.3.6/app/views/admin/assets/remove.html.haml
= stylesheet_link_tag 'admin/assets'

%h1= t("clipped_extension.remove_asset")
%p.warning= t("clipped_extension.confirm_remove_asset")

%table.index#assets{:cellpadding => "0", :cellspacing => "0", :border => "0"}
  %tbody
    %tr[@asset]
      %td.icon= image_tag @asset.thumbnail(:icon), :title => @asset.asset_file_name
      %td.name= @asset.title

= form_for [:admin, @asset], :html => { :method => 'delete' } do
  .buttons
    %input.button{:type => "submit", :value => t("clipped_extension.delete_asset")}
    = t("or")
    = link_to t("cancel"), admin_assets_path